
services:
  learningapp-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: learning_framework
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    image: php:8.1-fpm
    container_name: learning_php
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0
    container_name: learning_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
